.TH "D:/Temp/EDA-LESIPL/Aulas Directory Reference" 3 "Tue Mar 22 2022" "Version 1.0" "Listas Ligadas Simples" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Temp/EDA-LESIPL/Aulas Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBAula 4 \- Listas Ligadas\fP"
.br
.in -1c
