.TH "Jogo" 3 "Tue Mar 22 2022" "Version 1.0" "Listas Ligadas Simples" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Jogo \- Estrutura para armazenar um jogo\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Dados\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBcod\fP"
.br
.ti -1c
.RI "char \fBnome\fP [\fBN\fP]"
.br
.ti -1c
.RI "char \fBtipo\fP"
.br
.ti -1c
.RI "struct \fBJogo\fP * \fBnext\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Estrutura para armazenar um jogo\&. 

Um jogo contém um código (@cod), nome (@nome) e um tipo (@tipo)\&. 
.SH "Field Documentation"
.PP 
.SS "int cod"

.SS "struct \fBJogo\fP* next"
apontador para próximo jogo 
.SS "char nome[\fBN\fP]"

.SS "char tipo"


.SH "Author"
.PP 
Generated automatically by Doxygen for Listas Ligadas Simples from the source code\&.
