.TH "D:/Temp/EDA-LESIPL/Aulas/Aula 4 - Listas Ligadas/Main.c" 3 "Tue Mar 22 2022" "Version 1.0" "Listas Ligadas Simples" \" -*- nroff -*-
.ad l
.nh
.SH NAME
D:/Temp/EDA-LESIPL/Aulas/Aula 4 - Listas Ligadas/Main.c \- Lista Ligadas Simples (versão 1)  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <locale\&.h>\fP
.br
\fC#include 'Dados\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX\fP   10"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Lista Ligadas Simples (versão 1) 


.PP
\fBAuthor:\fP
.RS 4
lufer @email lufer@ipca.pt 
.RE
.PP
\fBDate:\fP
.RS 4
2022 Manipulação de Lista Ligada Simples
.RE
.PP
\fBSee also:\fP
.RS 4
http://www.stack.nl/~dimitri/doxygen/docblocks.html 
.PP
http://www.stack.nl/~dimitri/doxygen/commands.html 
.PP
http://fnch.users.sourceforge.net/doxygen_c.html
.RE
.PP
\fBBug\fP
.RS 4
No known bugs\&. 
.RE
.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#define MAX   10"

.SH "Function Documentation"
.PP 
.SS "int main ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Listas Ligadas Simples from the source code\&.
